version: '3.8'

services:
  app:
    image: controletrabalhosapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TrabalhosDB;User=sa;Password=Your_password123
    command: >
      sh -c "dotnet ef database update && dotnet ControleDeTrabalhosAcademicos.dll"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
